# Site settings
title: "All the Ducks Are Swimming in the Water"
email: liz.and.chris.dukes@gmail.com
description: "Liz and Chris Dukes Family Blog"
baseurl: ""
#url: "http://yourdomain.com"
#twitter_username: jekyllrb
github_username:  lizandchris
# excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
permalink: pretty
collections:
  houses:
    output: true

# Other
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "houses"
    values:
      layout: "page"
